package com.smokinggunstudio.vezerfonal.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF00322f)
val LightOnPrimary = Color(0xFFffffff)
val LightSecondary = Color(0xFF00322f)
val LightOnSecondary = Color(0xFFffffff)
val LightTertiary = Color(0xFF003300)
val LightOnTertiary = Color(0xFFffffff)
val LightError = Color(0xFFF9FAFB)
val LightOnError = Color(0xFFffffff)
val LightPrimaryContainer = Color(0xFF00534d)
val LightOnPrimaryContainer = Color(0xFFffffff)
val LightSecondaryContainer = Color(0xFF00534e)
val LightOnSecondaryContainer = Color(0xFFffffff)
val LightTertiaryContainer = Color(0xFF00543f)
val LightOnTertiaryContainer = Color(0xFFffffff)
val LightErrorContainer = Color(0xFF98000a)
val LightOnErrorContainer = Color(0xFFffffff)
val LightSurfaceDim = Color(0xFFb7b9bf)
val LightSurface = Color(0xFFf8f9ff)
val LightSurfaceBright = Color(0xFFf8f9ff)
val LightInverseSurface = Color(0xFF2e3135)
val LightInverseOnSurface = Color(0xFFffffff)
val LightInversePrimary = Color(0xFF81d5cc)
val LightSurfaceContainerLowest = Color(0xFFffffff)
val LightSurfaceContainerLow = Color(0xFFeff0f7)
val LightSurfaceContainer = Color(0xFFe1e2e8)

val Keppel = Color(0xFF4DB6AC)
val DodgerBlue = Color(0xFF33A9FF)
val MediumAquamarine = Color(0xFF00D4A4)
val RichBlack = Color(0xFF0A0F0E)
val EerieBlack = Color(0xFF0B0F14)
val AliceBlueGray = Color(0xFFE2E8F0)
val RaisinBlack = Color(0xFF1A1F26)
val Cultured = Color(0xFFF1F5F9)
val CharcoalGray = Color(0xFF374151)

val White = Color(0xFFFFFFFF)
val Black = Color(0xFF000000)