ktor {
    application {
        modules = [ com.smokinggunstudio.vezerfonal.ApplicationKt.module ]
        paths {
            pfps = ${PFP_DIR}
            firebase = ${FIREBASE_CRED}
        }
    }
    database {
        url = ${DATABASE_URL}
        username = ${DB_USER}
        password = ${DB_PASSWORD}
    }
    deployment {
        port = 8080
        host = "127.0.0.1"
        maxRequestSize = 0
    }
}