ktor:
    application:
        modules:
            - com.smokinggunstudio.vezerfonal.ApplicationKt.module
        directories:
            pfps: ${PFP_DIR}
    database:
        url: ${DATABASE_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}